export enum Specialization {
  DEFAULT = 'UNDEFINED',

  JUNIOR_WORKER = 'JUNIOR_WORKER',

  MIDDLE_WORKER = 'MIDDLE_WORKER',

  SENIOR_WORKER = 'SENIOR_WORKER',

  TEAM_LEADER = 'TEAM_LEADER',

  DEPARTMENT_DIRECTOR = 'DEPARTMENT_DIRECTOR',

  FACTORY_DIRECTOR = 'FACTORY_DIRECTOR',

  CEO = 'CEO',

  SYSTEM_ADMIN = 'SYSTEM_ADMIN',

}
